apiVersion: v1
kind: Namespace
metadata:
  name: microservices-demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: microservices-demo
data:
  FLASK_ENV: "production"
  PYTHONUNBUFFERED: "1"
 
 # Service Ports and services
  PRODUCT_SERVICE_PORT: "5001"
  USER_SERVICE_PORT: "5002"
  ORDERS_SERVICE_PORT: "5003"
  REVIEWS_SERVICE_PORT: "5004"
---
apiVersion: v1
kind: Secret
metadata:
  name: common-secret
  namespace: microservices-demo
type: Opaque
stringData:
  SECRET_KEY: "P@ssw0rd123!"
  